import type { Candidate } from '../types/candidate'

export const mockCandidates: Candidate[] = [
  {
    id: 'ivanov',
    name: 'Иванов Иван Иванович',
    position: 'react-middle',
    pos_label: 'React — ведущий программист',
    email: 'ivanov@email.com',
    phone: '+7 999 123-45-67',
    city: 'Бишкек',
    tg: '@ivanov_dev',
    exp: [['2022-01 — н.в.', 'TechCorp', 'Frontend Developer', '2 г.']],
    total_exp: '~3.5 г.',
    stack: 'React, TypeScript, Redux',
    edu: 'КНУ, Информатика, 2020',
    verdict: 'ПОДХОДИТ',
    vc: 'verdict-green',
    criteria: [['ok', 'React — есть']],
    summary: 'Опытный React-разработчик.',
    questions: ['Redux Toolkit — какой опыт?'],
    status: 'new',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'petrov',
    name: 'Петров Пётр Петрович',
    position: 'react-middle',
    pos_label: 'React — ведущий программист',
    email: 'petrov@email.com',
    phone: null,
    city: 'Ош',
    tg: '@petrov_dev',
    exp: [['2021-01 — н.в.', 'StartupHub', 'Developer', '4 г.']],
    total_exp: '~4 г.',
    stack: 'Vue, JavaScript',
    edu: 'КГТУ, ИТ, 2019',
    verdict: 'ЧАСТИЧНО',
    vc: 'verdict-orange',
    criteria: [['partial', 'Redux — частично использовал']],
    summary: 'Опыт с Vue, переходит на React.',
    questions: ['Готовы ли изучать React?'],
    status: 'review',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'sidorov',
    name: 'Сидоров Сидор Сидорович',
    position: 'react-junior',
    pos_label: 'React — junior программист',
    email: 'sidorov@email.com',
    phone: '+996 700 111-22-33',
    city: 'Каракол',
    tg: '@sidorov_dev',
    exp: [['2023-01 — н.в.', 'ITLab', 'Junior Developer', '1 г.']],
    total_exp: '~1 г.',
    stack: 'HTML, CSS',
    edu: 'НГУ, ИТ, 2022',
    verdict: 'НЕ СООТВЕТСТВУЕТ',
    vc: 'verdict-red',
    criteria: [['no', 'TypeScript — не использует']],
    summary: 'Junior без опыта React.',
    questions: ['Готовы начать со стажировки?'],
    status: 'rejected',
    createdAt: '2026-03-01T00:00:00Z',
  },
]
